//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP6_2Parcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        public int IDLIBRO { get; set; }
        public string TITULO { get; set; }
        public string AUTOR { get; set; }
        public string ISBN { get; set; }
        public string PAGINAS { get; set; }
        public string EDICION { get; set; }
        public string EDITORIAL { get; set; }
        public string CIUDAD { get; set; }
        public string PAIS { get; set; }
        public string FECHAEDICION { get; set; }
    }
}
